### ISSUE TITLE
Unable to check for list-or-dict

### ISSUE THREAD

**Issue by jdandrea** [alfredodeza/notario#12]
Steps to reproduce:

```
from notario import ensure, validate
from notario.decorators import instance_of

# See notario.decorators.instance_of() in documentation
@instance_of((list, dict))
def valid_custom(value):
    ensure(len(value) > 0)

schema = ('foo', valid_custom)

# Try an array - it works fine.
data = {'foo': [1, 2, 3]}
print "Trying to validate {}".format(data['foo'])
validate(data, schema)

# Try a dictionary regardless of the value (could be 'baz',
# could be a list, or another dict, doesn't matter).
data = {'foo': {'bar': 'baz'}}
print "Trying to validate {}".format(data['foo'])
validate(data, schema)
```

Output:

```
Trying to validate [1, 2, 3]
Trying to validate {'bar': 'baz'}
Traceback (most recent call last):
  File "foo.py", line 43, in <module>
    validate(data, schema)
  File "/usr/local/lib/python2.7/site-packages/notario/engine.py", line 288, in validate
    validator.validate()
  File "/usr/local/lib/python2.7/site-packages/notario/engine.py", line 19, in validate
    self.traverser(self.data, self.schema, [])
  File "/usr/local/lib/python2.7/site-packages/notario/engine.py", line 52, in traverser
    self.traverser(value, svalue, tree)
  File "/usr/local/lib/python2.7/site-packages/notario/engine.py", line 35, in traverser
    schema = self.sanitize_optionals(data, schema, tree)
  File "/usr/local/lib/python2.7/site-packages/notario/engine.py", line 125, in sanitize_optionals
    self.length_equality(data, schema, 0, tree)
  File "/usr/local/lib/python2.7/site-packages/notario/engine.py", line 112, in length_equality
    raise SchemaError(data, tree, reason=reason)
notario.exceptions.SchemaError: -> foo  has less items in schema than in data
```

**Comment by alfredodeza** [comment]
This has taken a while to get around to, sorry about that! I believe that this patch addresses the problem here @jdandrea https://github.com/alfredodeza/notario/commit/cc4bf5cfcd68e9e18ca1011be633f4f213144f3d 

If you could confirm that would be great, I've added your reproducer as a test though, so I am confident this will work.

**Comment by jdandrea** [comment]
Ooh, thank you so much! I will have a look asap. With the reproducer added, that ought to help as well.

**Comment by jdandrea** [comment]
It works! THANK YOU!

```
Trying to validate [1, 2, 3]
Trying to validate {'bar': 'baz'}
```
